name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main # This workflow runs when you push code to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # The type of virtual machine GitHub Actions will use

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # This step gets your code from the GitHub repository

    - name: Set up Python
      uses: actions/setup-python@v5 # Installs Python on the virtual computer
      with:
        python-version: '3.9' # Or 3.10, 3.11, etc. - should match what's on EC2

    - name: Deploy via SSH to EC2
      uses: appleboy/ssh-action@v0.1.10 # This action connects to your EC2 instance via SSH
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Change to the directory where your app is cloned on EC2
          # Replace 'YourRepoName' with the actual name of your repository folder
          cd first-flask # <--- REPLACE 'YourRepoName' HERE!

          # Pull the latest code from GitHub
          echo "Pulling latest code from GitHub..."
          git pull origin main

          # --- Virtual Environment Setup ---
          # Create virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            echo "Creating virtual environment..."
            python3 -m venv venv
          fi

          # Activate the virtual environment
          echo "Activating virtual environment..."
          source venv/bin/activate

          # Install any new or updated Python dependencies
          echo "Installing Python dependencies..."
          pip install -r requirements.txt

          # Stop the currently running Flask app (if any)
          echo "Stopping existing Flask app (if running)..."
          pkill -f 'python3 app.py' || true

          # Start the Flask app again in the background using nohup
          echo "Starting new Flask app..."
          # Use the python interpreter from the active virtual environment
          nohup python3 app.py > app.log 2>&1 &

          echo "Deployment complete! Check your EC2 public IP on port 5000."
