name: Flask App Build

on:
  push:
    branches:
      - main # This workflow will run every time you push code to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # This tells GitHub Actions to use a virtual computer with Ubuntu Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # This step gets your code from the GitHub repository

    - name: Set up Python
      uses: actions/setup-python@v5 # This step installs Python on the virtual computer
      with:
        python-version: '3.9' # You can specify a Python version, like 3.9, 3.10, 3.11, etc.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Upgrade pip, the Python package installer
        pip install -r requirements.txt # Install Flask and any other libraries from your requirements.txt

    - name: Check Flask app file exists
      run: |
        ls -l app.py # Just to confirm your app.py is there

    - name: Display Flask version (optional)
      run: |
        pip show Flask # Show information about the installed Flask package
